site_name: MK Worldwide
site_url: https://mkworldwide.dev
site_author: MK Worldwide
site_description: Official documentation for MK Worldwide projects

# Repository
repo_name: MKWorldWide/Home
repo_url: https://github.com/MKWorldWide/Home
edit_uri: edit/main/docs/

docs_dir: docs
site_dir: site

# Theme
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.share
    - content.tooltips
  favicon: assets/favicon.ico
  logo: assets/logo.png

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Guides:
    - AWS EC2 Setup: guides/aws-ec2-setup.md
    - CI/CD Pipeline: guides/ci-cd-pipeline.md
  - Reference:
    - API: reference/api.md
    - Configuration: reference/configuration.md
  - Legal:
    - Covenant: legal/COVENANT.md
    - License: legal/license.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true

# Extra
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Copyright
copyright: Copyright &copy; 2024 MK Worldwide
