name: Code Quality & Security

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.txt'
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  PYTHON_VERSION: '3.11'

concurrency:
  group: code-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0

      - name: Run Prettier
        run: npx prettier --check .

      - name: Check for secrets in code
        uses: gitleaks/gitleaks-action@v3
        with:
          config-path: .github/gitleaks.toml
          no-git: false
          verbose: true

  dependency-check:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run npm audit
        run: npm audit --production
        continue-on-error: true

      - name: Run dependency review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

  sast:
    name: Static Analysis (SAST)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v2
        with:
          config: p/security-audit
          output: semgrep-results.sarif
          severity: WARNING,ERROR

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

  notify:
    name: Notify Status
    needs: [code-quality, dependency-check, sast]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow status
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${{ github.repository }}:${{ github.head_ref || github.ref_name }}`,
            });

            if (pullRequests.length > 0) {
              const pr = pullRequests[0];
              const runUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `⚠️ Code quality checks failed! Please review the [workflow run](${runUrl}) for details.`
              });
            }
